---
engines:
  duplication:
    enabled: true
    config:
      languages:
      - javascript
  eslint:
    enabled: false
  fixme:
    enabled: true
    config:
      strings:
      - FIXME
      - BUG
      - CUSTOM
ratings:
  paths:
  - "**.js"
  - "**.jsx"
exclude_paths:
- config/*.js
- test/**/*.js
- e2e/**/*.js
- node_modules/**/*.js
- .codeclimate.yml
