language: node_js
sudo: false
install:
  - npm install
  - npm run style && npm run compile
  - export DISPLAY=':99.0'
  - Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
script:
  - npm run e2e
  - npm run test
cache:
  directories:
    - node_modules
addons:
  apt:
    packages:
      - xvfb
