language: node_js
sudo: false
install:
  - rm -rf node_modules
  - npm install
  - npm run compile
  - export DISPLAY=':99.0'
  - Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
script:
  - npm run test
  # - npm run e2e
addons:
  apt:
    packages:
      - xvfb

