environment:
  nodejs_version: ""

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install -g npm
  - npm --version
  - npm install
  - npm run compile

init:
  - git config --global core.autocrlf false

test_script:
  - node --version
  - npm run test

cache:
  - node_modules

build: off
deploy: off

