environment:
  nodejs_version: ""

install:
  - ps: Install-Product node $env:nodejs_version
  - rm -rf node_modules
  - npm install -g npm
  - npm --version
  - npm install
  - npm run compile

init:
  - git config --global core.autocrlf false

test_script:
  - node --version
  - npm run test

build: off
deploy: off

