environment:
  nodejs_version: ""

install:
  - ps: Install-Product node $env:nodejs_version
  - choco install cyg-get
  - type C:\ProgramData\chocolatey\logs\chocolatey.log
  - set PATH=%PATH%;C:\ProgramData\chocolatey\lib\Cygwin\tools\cygwin\bin
  - C:\ProgramData\chocolatey\bin\cyg-get.bat install gcc make
  - npm install -g npm
  - npm --version
  - npm install -g node-gyp
  - npm install
  - npm run compile

init:
  - git config --global core.autocrlf false

test_script:
  - node --version
  - npm run test

cache:
  - node_modules

build: off
deploy: off

